name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: CultureHQ/actions-yarn@v1.0.1
      - run: yarn
      - run: yarn build
      - name: Get Artifact Publish Token
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.4
        with:
          output-modes: environment
      - run: export HOST=docker-public.packages.atlassian.com/
      - run: export REPO=atlassianlabs/landkid
      - run: export TAG=`if [ "${GITHUB_REF##*/}" == "master" ]; then echo "latest"; else echo $GITHUB_REF ; fi`
      - run: docker login $HOST --username $ARTIFACTORY_USERNAME --password $ARTIFACTORY_API_KEY
      - run: docker build -f Dockerfile -t $REPO:$GITHUB_SHA .
      - run: docker tag $REPO:$GITHUB_SHA $HOST$REPO:$TAG
      - run: docker tag $REPO:$GITHUB_SHA $HOST$REPO:action-${{github.run_number}}
      - run: docker push $HOST$REPO:$TAG
      - run: docker push $HOST$REPO:action-${{github.run_number}}
